import Foundation

extension AppConfiguration {
    init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        self.minimumCashReserve = try c.decode(Double.self, forKey: .minimumCashReserve)
        self.initialAccountBalance = try c.decode(Double.self, forKey: .initialAccountBalance)
        self.poolBalanceDistributionStrategy = try c.decode(PoolBalanceDistributionStrategy.self, forKey: .poolBalanceDistributionStrategy)
        self.poolBalanceDistributionThreshold = try c.decode(Double.self, forKey: .poolBalanceDistributionThreshold)
        self.traderCommissionRate = try c.decodeIfPresent(Double.self, forKey: .traderCommissionRate)
        self.appCommissionRate = try c.decodeIfPresent(Double.self, forKey: .appCommissionRate)
        self.investorCommissionRateTotal = try c.decodeIfPresent(Double.self, forKey: .investorCommissionRateTotal)
        self.appServiceChargeRate = try c.decodeIfPresent(Double.self, forKey: .appServiceChargeRate)
            ?? c.decodeIfPresent(Double.self, forKey: .platformServiceChargeRate)
        self.appServiceChargeRateCompanies = try c.decodeIfPresent(Double.self, forKey: .appServiceChargeRateCompanies)
            ?? c.decodeIfPresent(Double.self, forKey: .platformServiceChargeRateCompanies)
            ?? self.appServiceChargeRate
        self.showCommissionBreakdownInCreditNote = try c.decodeIfPresent(Bool.self, forKey: .showCommissionBreakdownInCreditNote)
        self.showDocumentReferenceLinksInAccountStatement = try c.decodeIfPresent(
            Bool.self,
            forKey: .showDocumentReferenceLinksInAccountStatement
        )
        self.maximumRiskExposurePercent = try c.decodeIfPresent(Double.self, forKey: .maximumRiskExposurePercent)
        self.walletFeatureEnabled = try c.decodeIfPresent(Bool.self, forKey: .walletFeatureEnabled)
        self.serviceChargeInvoiceFromBackend = try c.decodeIfPresent(Bool.self, forKey: .serviceChargeInvoiceFromBackend)
        self.serviceChargeLegacyClientFallbackEnabled = try c.decodeIfPresent(Bool.self, forKey: .serviceChargeLegacyClientFallbackEnabled)
        self.investorMonetaryServerOnly = try c.decodeIfPresent(Bool.self, forKey: .investorMonetaryServerOnly)
        self.collectionBillServerLegs = try c.decodeIfPresent(Bool.self, forKey: .collectionBillServerLegs)
        self.traderMonetaryServerOnly = try c.decodeIfPresent(Bool.self, forKey: .traderMonetaryServerOnly)
        self.frontendReadonlyMode = try c.decodeIfPresent(Bool.self, forKey: .frontendReadonlyMode)
        self.showInvestorPartialSellRealizations = try c.decodeIfPresent(Bool.self, forKey: .showInvestorPartialSellRealizations)
        self.showTraderDashboardInvestmentActiveStatus = try c.decodeIfPresent(
            Bool.self,
            forKey: .showTraderDashboardInvestmentActiveStatus
        )
        self.dailyTransactionLimit = try c.decodeIfPresent(Double.self, forKey: .dailyTransactionLimit)
        self.weeklyTransactionLimit = try c.decodeIfPresent(Double.self, forKey: .weeklyTransactionLimit)
        self.monthlyTransactionLimit = try c.decodeIfPresent(Double.self, forKey: .monthlyTransactionLimit)
        self.minInvestment = try c.decodeIfPresent(Double.self, forKey: .minInvestment)
        self.maxInvestment = try c.decodeIfPresent(Double.self, forKey: .maxInvestment)
        self.maxPoolMirrorBuyOrderAmount = try c.decodeIfPresent(Double.self, forKey: .maxPoolMirrorBuyOrderAmount)
        self.minTraderBuyOrderAmount = try c.decodeIfPresent(Double.self, forKey: .minTraderBuyOrderAmount)
        self.maxTraderPartialSells = try c.decodeIfPresent(Int.self, forKey: .maxTraderPartialSells)
        self.taxCollectionMode = try c.decodeIfPresent(String.self, forKey: .taxCollectionMode)
        self.userMinimumCashReserves = try c.decode([String: Double].self, forKey: .userMinimumCashReserves)
        self.slaMonitoringInterval = try c.decode(TimeInterval.self, forKey: .slaMonitoringInterval)
        self.lastUpdated = try c.decode(Date.self, forKey: .lastUpdated)
        self.updatedBy = try c.decode(String.self, forKey: .updatedBy)
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.container(keyedBy: CodingKeys.self)
        try c.encode(self.minimumCashReserve, forKey: .minimumCashReserve)
        try c.encode(self.initialAccountBalance, forKey: .initialAccountBalance)
        try c.encode(self.poolBalanceDistributionStrategy, forKey: .poolBalanceDistributionStrategy)
        try c.encode(self.poolBalanceDistributionThreshold, forKey: .poolBalanceDistributionThreshold)
        try c.encodeIfPresent(self.traderCommissionRate, forKey: .traderCommissionRate)
        try c.encodeIfPresent(self.appCommissionRate, forKey: .appCommissionRate)
        try c.encodeIfPresent(self.investorCommissionRateTotal, forKey: .investorCommissionRateTotal)
        try c.encodeIfPresent(self.appServiceChargeRate, forKey: .appServiceChargeRate)
        try c.encodeIfPresent(self.appServiceChargeRateCompanies, forKey: .appServiceChargeRateCompanies)
        try c.encodeIfPresent(self.showCommissionBreakdownInCreditNote, forKey: .showCommissionBreakdownInCreditNote)
        try c.encodeIfPresent(self.showDocumentReferenceLinksInAccountStatement, forKey: .showDocumentReferenceLinksInAccountStatement)
        try c.encodeIfPresent(self.maximumRiskExposurePercent, forKey: .maximumRiskExposurePercent)
        try c.encodeIfPresent(self.walletFeatureEnabled, forKey: .walletFeatureEnabled)
        try c.encodeIfPresent(self.serviceChargeInvoiceFromBackend, forKey: .serviceChargeInvoiceFromBackend)
        try c.encodeIfPresent(self.serviceChargeLegacyClientFallbackEnabled, forKey: .serviceChargeLegacyClientFallbackEnabled)
        try c.encodeIfPresent(self.investorMonetaryServerOnly, forKey: .investorMonetaryServerOnly)
        try c.encodeIfPresent(self.collectionBillServerLegs, forKey: .collectionBillServerLegs)
        try c.encodeIfPresent(self.traderMonetaryServerOnly, forKey: .traderMonetaryServerOnly)
        try c.encodeIfPresent(self.frontendReadonlyMode, forKey: .frontendReadonlyMode)
        try c.encodeIfPresent(self.showInvestorPartialSellRealizations, forKey: .showInvestorPartialSellRealizations)
        try c.encodeIfPresent(self.showTraderDashboardInvestmentActiveStatus, forKey: .showTraderDashboardInvestmentActiveStatus)
        try c.encodeIfPresent(self.dailyTransactionLimit, forKey: .dailyTransactionLimit)
        try c.encodeIfPresent(self.weeklyTransactionLimit, forKey: .weeklyTransactionLimit)
        try c.encodeIfPresent(self.monthlyTransactionLimit, forKey: .monthlyTransactionLimit)
        try c.encodeIfPresent(self.minInvestment, forKey: .minInvestment)
        try c.encodeIfPresent(self.maxInvestment, forKey: .maxInvestment)
        try c.encodeIfPresent(self.maxPoolMirrorBuyOrderAmount, forKey: .maxPoolMirrorBuyOrderAmount)
        try c.encodeIfPresent(self.minTraderBuyOrderAmount, forKey: .minTraderBuyOrderAmount)
        try c.encodeIfPresent(self.maxTraderPartialSells, forKey: .maxTraderPartialSells)
        try c.encodeIfPresent(self.taxCollectionMode, forKey: .taxCollectionMode)
        try c.encode(self.userMinimumCashReserves, forKey: .userMinimumCashReserves)
        try c.encode(self.slaMonitoringInterval, forKey: .slaMonitoringInterval)
        try c.encode(self.lastUpdated, forKey: .lastUpdated)
        try c.encode(self.updatedBy, forKey: .updatedBy)
    }
}
