'use strict';

const FAQ_CATEGORIES = [
  { slug: 'app_overview', title: 'App-Übersicht', displayName: 'App-Übersicht', icon: 'info.circle', showOnLanding: true, showInHelpCenter: true, showInCSR: true, sortOrder: 1, targetRoles: null },
  { slug: 'getting_started', title: 'Erste Schritte', displayName: 'Erste Schritte', icon: 'play.circle', showOnLanding: true, showInHelpCenter: true, showInCSR: true, sortOrder: 2, targetRoles: null },
  { slug: 'investments', title: 'Investitionen', displayName: 'Investitionen', icon: 'chart.line.uptrend.xyaxis', showOnLanding: true, showInHelpCenter: true, showInCSR: true, sortOrder: 3, targetRoles: ['investor'] },
  { slug: 'trading', title: 'Trading', displayName: 'Trading', icon: 'arrow.left.arrow.right', showOnLanding: false, showInHelpCenter: true, showInCSR: true, sortOrder: 5, targetRoles: ['trader'] },
  { slug: 'invoices', title: 'Rechnungen & Auszüge', displayName: 'Rechnungen & Auszüge', icon: 'doc.text', showOnLanding: false, showInHelpCenter: true, showInCSR: true, sortOrder: 7, targetRoles: ['trader'] },
  { slug: 'security', title: 'Sicherheit & Authentifizierung', displayName: 'Sicherheit & Authentifizierung', icon: 'lock.shield', showOnLanding: false, showInHelpCenter: true, showInCSR: true, sortOrder: 10, targetRoles: null },
  { slug: 'notifications', title: 'Benachrichtigungen', displayName: 'Benachrichtigungen', icon: 'bell', showOnLanding: false, showInHelpCenter: true, showInCSR: true, sortOrder: 11, targetRoles: null },
  { slug: 'technical', title: 'Technischer Support', displayName: 'Technischer Support', icon: 'wrench.and.screwdriver', showOnLanding: false, showInHelpCenter: true, showInCSR: true, sortOrder: 12, targetRoles: null },
];

const FAQ_ARTICLES = [
  { faqId: 'faq-platform-what', categorySlug: 'app_overview', question: 'Was ist {{APP_NAME}}?', answer: '{{APP_NAME}} ist eine innovative Investment-App, die Investoren mit erfahrenen Tradern verbindet. Investoren können ihr Kapital in Trades von erfahrenen Tradern investieren und an deren Erfolg partizipieren - ohne sich ausführlich mit der Trading-Materie befassen zu müssen.', sortOrder: 1, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-pool-system', categorySlug: 'app_overview', question: 'Wie funktioniert das Investment-Pool-System?', answer: 'Die Investments der Investoren sind dem von Ihnen gewählten Trader zugeordnet. Handelt der Trader, wird ein simultaner Trade mit dem entsprechenden (Pool-)Kapital der Investoren ausgeführt. Gewinne werden proportional auf alle am Trade beteiligten Investoren verteilt, abzüglich einer Provision für den Trader.', sortOrder: 2, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-who-can-use', categorySlug: 'app_overview', question: 'Wer kann die App nutzen?', answer: 'Jede natürliche Person ab 18 Jahren mit Wohnsitz in Deutschland oder der EU kann sich registrieren. Für die vollständige Nutzung ist eine Identitätsprüfung (KYC) erforderlich.', sortOrder: 3, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-data-privacy', categorySlug: 'app_overview', question: 'Wie werden meine Daten geschützt?', answer: 'Ihre Daten werden verschlüsselt übertragen und gespeichert. Wir halten die geltenden Datenschutzbestimmungen (DSGVO) ein. Details finden Sie in unserer Datenschutzerklärung unter Profil → Rechtliches.', sortOrder: 4, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-register', categorySlug: 'getting_started', question: 'Wie kann ich mich registrieren?', answer: 'Tippen Sie auf "Get Started" und folgen Sie dem Registrierungsprozess. Sie werden Ihre persönlichen Daten eingeben, Ihre Identität verifizieren und eine Risikoklassifizierung durchlaufen.', sortOrder: 1, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-kyc-process', categorySlug: 'getting_started', question: 'Was ist die KYC-Verifizierung?', answer: 'KYC (Know Your Customer) ist eine gesetzlich vorgeschriebene Identitätsprüfung. Sie benötigen einen gültigen Personalausweis oder Reisepass. Der Prozess dauert in der Regel nur wenige Minuten.', sortOrder: 2, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-minimum-investment', categorySlug: 'getting_started', question: 'Was ist der Mindestinvestmentbetrag?', answer: 'Der Mindestinvestmentbetrag beträgt {{MIN_INVESTMENT}}. Sie können jederzeit weitere Beträge einzahlen oder Ihre Anlage erhöhen.', sortOrder: 3, isPublished: true, isPublic: true, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-invest-trader', categorySlug: 'investments', question: 'Wie kann ich in einen Trader investieren?', answer: 'Navigieren Sie zur Trader-Übersicht, wählen Sie einen Trader aus, der zu Ihrem Risikoprofil passt, und tippen Sie auf "Investieren". Geben Sie den gewünschten Betrag ein und bestätigen Sie die Investition.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-risk-classes', categorySlug: 'investments', question: 'Was bedeuten die Risikoklassen?', answer: 'Die Risikoklassen reichen von 1 (konservativ) bis 7 (spekulativ). Sie werden bei der Registrierung anhand Ihrer Erfahrung und finanziellen Situation eingestuft. Sie können nur in Trader investieren, deren Risikoklasse zu Ihrer passt.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-withdraw-investment', categorySlug: 'investments', question: 'Wie ziehe ich meine Investition zurück?', answer: 'Öffnen Sie das Investment-Detail, tippen Sie auf "Auszahlen" und geben Sie den gewünschten Betrag ein. Die Auszahlung wird innerhalb von 1–3 Werktagen auf Ihr Referenzkonto überwiesen.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-investor-fees', categorySlug: 'investments', question: 'Welche Gebühren fallen für Investoren an?', answer: 'Investoren zahlen eine Servicegebühr von {{APP_SERVICE_CHARGE_RATE}} p.a. auf das investierte Kapital sowie eine Gewinnbeteiligung (Performance Fee), die vom jeweiligen Trader festgelegt wird. Alle Gebühren werden transparent in der App angezeigt.', sortOrder: 4, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-investment-guarantee', categorySlug: 'investments', question: 'Ist meine Anlage garantiert?', answer: 'Nein. {{APP_NAME}} garantiert keine Renditen. Jede Anlage birgt Risiken; Sie können Ihr eingesetztes Kapital verlieren. Bitte investieren Sie nur Beträge, deren Verlust Sie verkraften können.', sortOrder: 5, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-investor-portfolio-overview', categorySlug: 'investments', question: 'Wo sehe ich meine Investment-Performance?', answer: 'Auf dem Dashboard und unter Investments finden Sie eine Übersicht über Ihre Investments, inklusive Gewinn/Verlust, aktueller Wert und Performance-Chart. Tippen Sie auf einzelne Investments für Details.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-investor-diversification', categorySlug: 'investments', question: 'Wie diversifiziere ich meine Investments?', answer: 'Sie können in mehrere Trader mit unterschiedlichen Strategien und Risikoklassen investieren. Die App zeigt Ihnen eine Übersicht Ihrer Diversifizierung und gibt Hinweise, wenn Ihre Investments zu konzentriert sind.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-investor-reports', categorySlug: 'investments', question: 'Wo finde ich meine Steuerbescheinigung?', answer: 'Steuerbescheinigungen werden jährlich automatisch erstellt und stehen unter Profil → Dokumente zum Download bereit. Sie erhalten eine Benachrichtigung, sobald das Dokument verfügbar ist.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['investor'] },
  { faqId: 'faq-place-order', categorySlug: 'trading', question: 'Wie platziere ich eine Order?', answer: 'Im Trading-Bereich können Sie **Derivate** (z. B. Optionsscheine, Zertifikate) suchen und Orders platzieren. Nutzen Sie die Suche nach WKN, ISIN oder Produktname. Wählen Sie das Produkt, geben Sie die Stückzahl ein und den Ordertyp (Market oder Limit). **Kein** eigenständiger Kassamarkthandel mit Aktien oder Spot-Devisen — Aktienkurse oder Indizes können nur als **Basiswert** eines Derivats vorkommen.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-tradable-instruments', categorySlug: 'trading', question: 'Welche Instrumente kann ich handeln?', answer: 'Über {{APP_NAME}} handeln Sie **strukturierte Derivate**, etwa Optionsscheine sowie Zertifikate (z. B. Knock-Outs, Bonus- oder Faktor-Zertifikate). Die Auswahl erfolgt per Suche nach **WKN**, **ISIN** oder Name. Nicht angeboten werden: reiner Kassamarkthandel mit Einzelaktien, Spot-Forex oder Rohstoff-Cash. Namen von Unternehmen, Indizes oder Währungspaaren erscheinen ggf. nur als **Basiswerte** der Produkte. Verfügbarkeit hängt von Marktzugang und Kontofreigaben ab.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-order-types', categorySlug: 'trading', question: 'Welche Ordertypen gibt es?', answer: 'Es gibt Market-Orders (sofortige Ausführung zum aktuellen Kurs) und Limit-Orders (Ausführung erst bei Erreichen eines bestimmten Kurses). Limit-Orders sind 30 Tage gültig.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-trading-hours', categorySlug: 'trading', question: 'Wann kann ich handeln?', answer: 'Der Handel mit Derivaten ist während der relevanten Börsen- und Handelszeiten möglich (z. B. Xetra: Mo–Fr 9:00–17:30 Uhr). Limit-Orders können jederzeit aufgegeben werden und werden bei Marktöffnung ausgeführt, wenn der Kurs erreicht wird.', sortOrder: 4, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-create-pool', categorySlug: 'trading', question: 'Wie erstelle ich einen Investment-Pool?', answer: 'Gehen Sie zu "Meine Pools" → "Neuen Pool erstellen". Definieren Sie Name, Strategie, Risikoklasse und Gebührenstruktur. Nach der Prüfung durch unser Compliance-Team wird der Pool für Investoren sichtbar.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-pool-commission', categorySlug: 'trading', question: 'Wie wird meine Provision berechnet?', answer: 'Ihre Provision setzt sich aus einer Verwaltungsgebühr und einer Performance Fee zusammen. Die Performance Fee wird nur auf Gewinne berechnet. Details finden Sie in Ihren Pool-Einstellungen und auf der monatlichen Abrechnung.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-pool-investors', categorySlug: 'trading', question: 'Wie sehe ich, wer in meinen Pool investiert hat?', answer: 'Unter "Meine Pools" → Pool-Detail → "Investoren" finden Sie eine anonymisierte Übersicht aller Investoren, deren Investitionsbetrag und -zeitpunkt. Aus Datenschutzgründen sind die Namen nicht sichtbar.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-trader-invoices', categorySlug: 'invoices', question: 'Wo finde ich meine Provisionsabrechnungen?', answer: 'Alle Provisionsabrechnungen und Gutschriften finden Sie unter Profil → Dokumente → Abrechnungen. Monatliche Abrechnungen werden automatisch am 5. des Folgemonats erstellt.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-trader-payout', categorySlug: 'invoices', question: 'Wann erhalte ich meine Auszahlung?', answer: 'Provisionen werden monatlich abgerechnet. Die Auszahlung erfolgt automatisch innerhalb von 5 Werktagen nach Rechnungsstellung auf Ihr hinterlegtes Bankkonto.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: ['trader'] },
  { faqId: 'faq-2fa', categorySlug: 'security', question: 'Wie aktiviere ich die Zwei-Faktor-Authentifizierung?', answer: 'Gehen Sie zu Profil → Sicherheit → Zwei-Faktor-Authentifizierung. Sie können zwischen TOTP (Authenticator-App) und biometrischer Authentifizierung (Face ID / Touch ID) wählen.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-password-reset', categorySlug: 'security', question: 'Wie setze ich mein Passwort zurück?', answer: 'Tippen Sie auf dem Login-Bildschirm auf "Passwort vergessen?". Sie erhalten einen Link per E-Mail, über den Sie ein neues Passwort festlegen können. Der Link ist 24 Stunden gültig.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-data-security', categorySlug: 'security', question: 'Wie sicher sind meine Daten?', answer: 'Wir setzen branchenübliche Sicherheitsmaßnahmen ein: verschlüsselte Übertragung (TLS), sichere Speicherung sensibler Daten und Einhaltung der DSGVO. Zwei-Faktor-Authentifizierung erhöht den Schutz Ihres Kontos.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-push-notifications', categorySlug: 'notifications', question: 'Welche Benachrichtigungen erhalte ich?', answer: 'Sie erhalten Push-Benachrichtigungen zu wichtigen Kontobewegungen, Sicherheitsereignissen und Statusänderungen. In den Einstellungen können Sie einzelne Kategorien aktivieren oder deaktivieren.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-app-crash', categorySlug: 'technical', question: 'Die App stürzt ab – was kann ich tun?', answer: 'Stellen Sie sicher, dass Sie die neueste App-Version verwenden (App Store → Updates). Falls das Problem weiterbesteht, löschen Sie die App und installieren Sie sie neu. Ihre Daten bleiben erhalten.', sortOrder: 1, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-connectivity', categorySlug: 'technical', question: 'Verbindungsprobleme – was soll ich tun?', answer: 'Prüfen Sie Ihre Internetverbindung. Falls die App keine Verbindung zum Server herstellen kann, starten Sie die App neu. Bei anhaltenden Problemen kontaktieren Sie bitte unseren Support.', sortOrder: 2, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
  { faqId: 'faq-app-update', categorySlug: 'technical', question: 'Wie aktualisiere ich die App?', answer: 'Öffnen Sie den App Store (iOS) bzw. Play Store (Android), suchen Sie nach {{APP_NAME}} und tippen Sie auf "Aktualisieren". Wir empfehlen, immer die neueste Version zu nutzen, um Sicherheits- und Funktionsverbesserungen zu erhalten.', sortOrder: 3, isPublished: true, isPublic: false, isUserVisible: true, targetRoles: null },
];

module.exports = {
  FAQ_CATEGORIES,
  FAQ_ARTICLES,
};
