import Foundation

// MARK: - Mock Data Arrays
/// Mock data arrays for traders and instruments

// MARK: - Mock Watched Instruments
let mockWatchedInstruments = [
    MockInstrument(symbol: "AAPL", name: "Apple Inc.", currentPrice: 175.43, changePercent: 2.1, volume: 45678900, isFavorite: true),
    MockInstrument(symbol: "TSLA", name: "Tesla Inc.", currentPrice: 245.67, changePercent: -1.8, volume: 23456700, isFavorite: true),
    MockInstrument(symbol: "MSFT", name: "Microsoft Corp.", currentPrice: 312.89, changePercent: 0.9, volume: 34567800, isFavorite: false),
    MockInstrument(symbol: "GOOGL", name: "Alphabet Inc.", currentPrice: 134.56, changePercent: 1.2, volume: 12345600, isFavorite: true)
]

// MARK: - Mock Traders Data Arrays
// Consistent with the 10 seeded traders (TRD-2026-00001 … TRD-2026-00010)
let mockTraders = [
    MockTrader(
        name: "Jan Becker",
        username: "jbecker",
        specialization: "DAX Optionsscheine",
        experienceYears: 12,
        isVerified: true,
        performance: 45.2,
        totalTrades: 189,
        winRate: 85.2,
        averageReturn: 22.1,
        totalReturn: 45.2,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.85, avgReturn: 22.1),
        lastNTrades: 20,
        successfulTradesInLastN: 17,
        averageReturnLastNTrades: 22.1,
        consecutiveWinningTrades: 9,
        maxDrawdown: -9.1,
        sharpeRatio: 1.8
    ),
    MockTrader(
        name: "Alexander Wolf",
        username: "awolf",
        specialization: "Call-Optionsscheine",
        experienceYears: 8,
        isVerified: true,
        performance: 31.2,
        totalTrades: 234,
        winRate: 81.5,
        averageReturn: 18.9,
        totalReturn: 31.2,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.81, avgReturn: 18.9),
        lastNTrades: 20,
        successfulTradesInLastN: 18,
        averageReturnLastNTrades: 18.9,
        consecutiveWinningTrades: 7,
        maxDrawdown: -12.8,
        sharpeRatio: 1.5
    ),
    MockTrader(
        name: "Lena Wagner",
        username: "lwagner",
        specialization: "Knock-Out-Zertifikate",
        experienceYears: 6,
        isVerified: true,
        performance: 24.5,
        totalTrades: 156,
        winRate: 78.2,
        averageReturn: 12.3,
        totalReturn: 24.5,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.78, avgReturn: 12.3),
        lastNTrades: 20,
        successfulTradesInLastN: 16,
        averageReturnLastNTrades: 12.3,
        consecutiveWinningTrades: 5,
        maxDrawdown: -8.5,
        sharpeRatio: 1.2
    ),
    MockTrader(
        name: "Tobias Hoffmann",
        username: "thoffmann",
        specialization: "Bonus-Zertifikate",
        experienceYears: 15,
        isVerified: true,
        performance: 67.8,
        totalTrades: 298,
        winRate: 89.3,
        averageReturn: 28.5,
        totalReturn: 67.8,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.89, avgReturn: 28.5),
        lastNTrades: 20,
        successfulTradesInLastN: 18,
        averageReturnLastNTrades: 28.5,
        consecutiveWinningTrades: 12,
        maxDrawdown: -18.7,
        sharpeRatio: 2.1
    ),
    MockTrader(
        name: "Julia Richter",
        username: "jrichter",
        specialization: "Faktor-Zertifikate",
        experienceYears: 7,
        isVerified: true,
        performance: 18.7,
        totalTrades: 89,
        winRate: 72.1,
        averageReturn: 15.8,
        totalReturn: 18.7,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.72, avgReturn: 15.8),
        lastNTrades: 20,
        successfulTradesInLastN: 14,
        averageReturnLastNTrades: 15.8,
        consecutiveWinningTrades: 3,
        maxDrawdown: -15.2,
        sharpeRatio: 0.9
    ),
    MockTrader(
        name: "Markus Klein",
        username: "mklein",
        specialization: "Hebel-Produkte",
        experienceYears: 10,
        isVerified: true,
        performance: 32.1,
        totalTrades: 145,
        winRate: 76.8,
        averageReturn: 16.4,
        totalReturn: 32.1,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.77, avgReturn: 16.4),
        lastNTrades: 20,
        successfulTradesInLastN: 15,
        averageReturnLastNTrades: 16.4,
        consecutiveWinningTrades: 6,
        maxDrawdown: -7.9,
        sharpeRatio: 1.3
    ),
    MockTrader(
        name: "Anna Lehmann",
        username: "alehmann",
        specialization: "Mini-Future-Zertifikate",
        experienceYears: 5,
        isVerified: true,
        performance: 14.3,
        totalTrades: 67,
        winRate: 68.9,
        averageReturn: 9.7,
        totalReturn: 14.3,
        riskLevel: .low,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.69, avgReturn: 9.7),
        lastNTrades: 20,
        successfulTradesInLastN: 14,
        averageReturnLastNTrades: 9.7,
        consecutiveWinningTrades: 4,
        maxDrawdown: -6.3,
        sharpeRatio: 0.8
    ),
    MockTrader(
        name: "Florian Schmitt",
        username: "fschmitt",
        specialization: "Volatilitäts-Trading",
        experienceYears: 14,
        isVerified: true,
        performance: 52.4,
        totalTrades: 312,
        winRate: 83.7,
        averageReturn: 24.6,
        totalReturn: 52.4,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.84, avgReturn: 24.6),
        lastNTrades: 20,
        successfulTradesInLastN: 17,
        averageReturnLastNTrades: 24.6,
        consecutiveWinningTrades: 8,
        maxDrawdown: -14.1,
        sharpeRatio: 1.7
    ),
    MockTrader(
        name: "Laura Koch",
        username: "lkoch",
        specialization: "Turbo-Optionsscheine",
        experienceYears: 6,
        isVerified: true,
        performance: 21.9,
        totalTrades: 98,
        winRate: 74.5,
        averageReturn: 13.2,
        totalReturn: 21.9,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.75, avgReturn: 13.2),
        lastNTrades: 20,
        successfulTradesInLastN: 15,
        averageReturnLastNTrades: 13.2,
        consecutiveWinningTrades: 5,
        maxDrawdown: -10.3,
        sharpeRatio: 1.1
    ),
    MockTrader(
        name: "Niklas Hartmann",
        username: "nhartmann",
        specialization: "Discount-Zertifikate",
        experienceYears: 9,
        isVerified: true,
        performance: 28.6,
        totalTrades: 176,
        winRate: 79.8,
        averageReturn: 14.7,
        totalReturn: 28.6,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.80, avgReturn: 14.7),
        lastNTrades: 20,
        successfulTradesInLastN: 16,
        averageReturnLastNTrades: 14.7,
        consecutiveWinningTrades: 6,
        maxDrawdown: -8.9,
        sharpeRatio: 1.4
    ),
]

// MARK: - Mock Watched Traders
// Subset of mockTraders (indices 0=Becker, 3=Hoffmann, 7=Schmitt) — no duplication
let mockWatchedTraders = [mockTraders[0], mockTraders[3], mockTraders[7]]
