import Foundation

// MARK: - Mock Data Arrays
/// Mock data arrays for traders and instruments

// MARK: - Mock Watched Instruments
let mockWatchedInstruments = [
    MockInstrument(symbol: "AAPL", name: "Apple Inc.", currentPrice: 175.43, changePercent: 2.1, volume: 45678900, isFavorite: true),
    MockInstrument(symbol: "TSLA", name: "Tesla Inc.", currentPrice: 245.67, changePercent: -1.8, volume: 23456700, isFavorite: true),
    MockInstrument(symbol: "MSFT", name: "Microsoft Corp.", currentPrice: 312.89, changePercent: 0.9, volume: 34567800, isFavorite: false),
    MockInstrument(symbol: "GOOGL", name: "Alphabet Inc.", currentPrice: 134.56, changePercent: 1.2, volume: 12345600, isFavorite: true)
]

// MARK: - Mock Traders Data Arrays
let mockTraders = [
    MockTrader(
        name: "Thomas Trader",
        username: "trader1",
        specialization: "Tech Stocks",
        experienceYears: 8,
        isVerified: true,
        performance: 24.5,
        totalTrades: 156,
        winRate: 78.2,
        averageReturn: 12.3,
        totalReturn: 24.5,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.78, avgReturn: 12.3),
        lastNTrades: 20,
        successfulTradesInLastN: 16,
        averageReturnLastNTrades: 12.3,
        consecutiveWinningTrades: 5,
        maxDrawdown: -8.5,
        sharpeRatio: 1.2
    ),
    MockTrader(
        name: "Alex Chen",
        username: "trader2",
        specialization: "Cryptocurrency",
        experienceYears: 5,
        isVerified: true,
        performance: 18.7,
        totalTrades: 89,
        winRate: 72.1,
        averageReturn: 15.8,
        totalReturn: 18.7,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.72, avgReturn: 15.8),
        lastNTrades: 20,
        successfulTradesInLastN: 14,
        averageReturnLastNTrades: 15.8,
        consecutiveWinningTrades: 3,
        maxDrawdown: -15.2,
        sharpeRatio: 0.9
    ),
    MockTrader(
        name: "Maria Rodriguez",
        username: "trader3",
        specialization: "Options Trading",
        experienceYears: 12,
        isVerified: true,
        performance: 31.2,
        totalTrades: 234,
        winRate: 81.5,
        averageReturn: 18.9,
        totalReturn: 31.2,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.81, avgReturn: 18.9),
        lastNTrades: 20,
        successfulTradesInLastN: 18,
        averageReturnLastNTrades: 18.9,
        consecutiveWinningTrades: 7,
        maxDrawdown: -12.8,
        sharpeRatio: 1.5
    ),
    MockTrader(
        name: "Emily Davis",
        username: "emilyd",
        specialization: "Commodities",
        experienceYears: 6,
        isVerified: false,
        performance: 14.3,
        totalTrades: 67,
        winRate: 68.9,
        averageReturn: 9.7,
        totalReturn: 14.3,
        riskLevel: .low,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.69, avgReturn: 9.7),
        lastNTrades: 20,
        successfulTradesInLastN: 14,
        averageReturnLastNTrades: 9.7,
        consecutiveWinningTrades: 4,
        maxDrawdown: -6.3,
        sharpeRatio: 0.8
    ),
    MockTrader(
        name: "David Wilson",
        username: "dwilson",
        specialization: "Forex",
        experienceYears: 10,
        isVerified: true,
        performance: 45.2,
        totalTrades: 189,
        winRate: 85.2,
        averageReturn: 22.1,
        totalReturn: 45.2,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.85, avgReturn: 22.1),
        lastNTrades: 20,
        successfulTradesInLastN: 17,
        averageReturnLastNTrades: 22.1,
        consecutiveWinningTrades: 9,
        maxDrawdown: -9.1,
        sharpeRatio: 1.8
    ),
    MockTrader(
        name: "Lisa Rodriguez",
        username: "lrodriguez",
        specialization: "ETF Trading",
        experienceYears: 7,
        isVerified: true,
        performance: 67.8,
        totalTrades: 145,
        winRate: 89.3,
        averageReturn: 28.5,
        totalReturn: 67.8,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.89, avgReturn: 28.5),
        lastNTrades: 20,
        successfulTradesInLastN: 18,
        averageReturnLastNTrades: 28.5,
        consecutiveWinningTrades: 12,
        maxDrawdown: -18.7,
        sharpeRatio: 2.1
    ),
    MockTrader(
        name: "Robert Kim",
        username: "rkim",
        specialization: "Bonds",
        experienceYears: 15,
        isVerified: true,
        performance: 32.1,
        totalTrades: 298,
        winRate: 76.8,
        averageReturn: 16.4,
        totalReturn: 32.1,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.77, avgReturn: 16.4),
        lastNTrades: 20,
        successfulTradesInLastN: 15,
        averageReturnLastNTrades: 16.4,
        consecutiveWinningTrades: 6,
        maxDrawdown: -7.9,
        sharpeRatio: 1.3
    )
]

// MARK: - Mock Watched Traders
let mockWatchedTraders = [
    MockTrader(
        name: "John Smith",
        username: "johnsmith",
        specialization: "Technology",
        experienceYears: 8,
        isVerified: true,
        performance: 45.2,
        totalTrades: 156,
        winRate: 78.5,
        averageReturn: 12.3,
        totalReturn: 45.2,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.78, avgReturn: 12.3),
        lastNTrades: 20,
        successfulTradesInLastN: 16,
        averageReturnLastNTrades: 12.3,
        consecutiveWinningTrades: 5,
        maxDrawdown: -8.5,
        sharpeRatio: 1.2
    ),
    MockTrader(
        name: "Sarah Johnson",
        username: "sarahj",
        specialization: "Cryptocurrency",
        experienceYears: 5,
        isVerified: true,
        performance: 67.8,
        totalTrades: 89,
        winRate: 82.1,
        averageReturn: 18.9,
        totalReturn: 67.8,
        riskLevel: .high,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.82, avgReturn: 18.9),
        lastNTrades: 20,
        successfulTradesInLastN: 16,
        averageReturnLastNTrades: 18.9,
        consecutiveWinningTrades: 8,
        maxDrawdown: -14.2,
        sharpeRatio: 1.4
    ),
    MockTrader(
        name: "Mike Chen",
        username: "mchen",
        specialization: "Healthcare",
        experienceYears: 12,
        isVerified: true,
        performance: 32.1,
        totalTrades: 234,
        winRate: 75.3,
        averageReturn: 9.8,
        totalReturn: 32.1,
        riskLevel: .medium,
        recentTrades: generateMockTradePerformance(count: 20, successRate: 0.75, avgReturn: 9.8),
        lastNTrades: 20,
        successfulTradesInLastN: 15,
        averageReturnLastNTrades: 9.8,
        consecutiveWinningTrades: 4,
        maxDrawdown: -6.8,
        sharpeRatio: 1.0
    )
]
