'use strict';

const PERMISSIONS = {
  admin: ['*'],
  business_admin: [
    'getAdminDashboard',
    // Tickets: nur Lese-Überblick (Bearbeitung/Erstellung über CSR)
    'getTickets',
    'getFinancialDashboard',
    'searchUsers',
    'getUserDetails',
    'getUserFinancialSummary',
    'getReports',
    'exportReport',
    'getFinancialReports',
    'getRevenueReport',
    'getFeeReport',
    'getCommissionReport',
    'getRoundingDifferencesReport',
    'getRoundingDifferences',
    'reviewRoundingDifference',
    'approveRoundingDifferenceResolution',
    'getBankReconciliation',
    'reviewBankReconciliation',
    'createCorrectionRequest',
    'getCorrectionRequests',
    'reviewCorrectionRequest',
    'getConfiguration',
    'requestConfigurationChange',
    'approveConfigurationChange',
    'rejectConfigurationChange',
    'getPendingConfigurationChanges',
    'getConfigurationChangeHistory',
    'getInvestmentsSummary',
    'getTradesSummary',
    'getPortfolioOverview',
    'getComplianceEvents',
    'getComplianceStatistics',
    'getPendingApprovals',
    'approveRequest',
    'rejectRequest',
    'getAuditLogs',
    'searchAuditLogs',
    'getInvoices',
    'getStatements',
    'regenerateStatement',
    'getSummaryReport',
    'getBankContraLedger',
    'getCompanyKybSubmissions',
    'getCompanyKybSubmissionDetail',
    'reviewCompanyKyb',
    'resetCompanyKyb',
  ],
  security_officer: [
    'getAdminDashboard',
    'getSecurityDashboard',
    'searchUsers',
    'getUserDetails',
    'getUserSecurityProfile',
    'getLoginHistory',
    'getFailedLoginAttempts',
    'getUserSessions',
    'terminateUserSession',
    'forcePasswordReset',
    'getSecurityEvents',
    'getSecurityAlerts',
    'reviewSecurityAlert',
    'markSecurityAlertResolved',
    'getDataAccessLogs',
    'getPermissionAudit',
    'getAdminActivityLog',
    'getComplianceEvents',
    'getComplianceStatistics',
    'getAuditLogs',
    'getAuditLogDetails',
    'searchAuditLogs',
    'exportAuditLogs',
    'getPendingReleases',
    'approveRelease',
    'rejectRelease',
    'getReleaseHistory',
    'getPendingApprovals',
    'approveRequest',
    'rejectRequest',
    'getSystemConfiguration',
    'getSecurityConfiguration',
    'getSecurityReports',
    'uploadSecurityReport',
  ],
  compliance: [
    'getAdminDashboard',
    'searchUsers',
    'getUserDetails',
    'getComplianceEvents',
    'getComplianceEventDetails',
    'reviewComplianceEvent',
    'markComplianceEventReviewed',
    'getPendingApprovals',
    'approveRequest',
    'rejectRequest',
    'getApprovalHistory',
    'getConfiguration',
    'approveConfigurationChange',
    'rejectConfigurationChange',
    'getPendingConfigurationChanges',
    'getConfigurationChangeHistory',
    'getAuditLogs',
    'getAuditLogDetails',
    'searchAuditLogs',
    'getReports',
    'exportReport',
    'getComplianceStatistics',
    'viewKYCStatus',
    'getKYCDocuments',
    'reviewKYCDocument',
    'getGDPRRequests',
    'processGDPRRequest',
    'exportUserData',
    'getLegalDocuments',
    'getLegalConsents',
    'getLegalDeliveryLogs',
    'getCompanyKybSubmissions',
    'getCompanyKybSubmissionDetail',
    'reviewCompanyKyb',
    'resetCompanyKyb',
  ],
  customer_service: [
    'getAdminDashboard',
    'searchUsers',
    'getUserDetails',
    'updateUserStatus_suspend',
    'updateUserStatus_reactivate',
    'getTickets',
    'getTicketDetails',
    'createTicket',
    'updateTicket',
    'assignTicket',
    'addTicketComment',
    'escalateTicket',
    'viewKYCStatus',
    'getKYCDocuments',
    'getCompanyKybSubmissions',
    'getCompanyKybSubmissionDetail',
    'getFAQs',
    'getFAQCategories',
    'sendUserNotification',
    'getUserNotificationHistory',
    'resetUserPassword',
    'unlockUserAccount',
    'resendVerificationEmail',
    'manageTemplates',
    'viewAnalytics',
  ],
  system: [
    'logComplianceEvent',
    'createAuditLog',
    'processScheduledJob',
    'sendSystemNotification',
    'updateSystemMetrics',
  ],
};

const STATUS_CHANGE_PERMISSIONS = {
  admin: ['pending', 'active', 'suspended', 'locked', 'closed', 'deleted'],
  business_admin: ['suspended', 'active'],
  security_officer: ['suspended', 'locked', 'active'],
  compliance: [],
  customer_service: ['suspended', 'active'],
};

module.exports = {
  PERMISSIONS,
  STATUS_CHANGE_PERMISSIONS,
};
