import type { ConfigurationParameter } from './types';

/** Parameter definitions with metadata (values come from backend / resolveConfig). */
export const PARAMETER_DEFINITIONS: Record<string, Omit<ConfigurationParameter, 'value'>> = {
  investorCommissionRateTotal: {
    key: 'investorCommissionRateTotal',
    displayName: 'Gesamtprovision Investor (= Summe)',
    description:
      'Exakte Provisions-Summe für Investoren (Collection Bill „Commission“). '
      + 'Muss immer gelten: Trader-Provision + App-Erfolgsprovision = dieser Wert (Gleichheit „=“, keine Obergrenze). '
      + 'Standard: 10 % (0,10) bei 5 % + 5 %.',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    hiddenInParameterList: true,
    min: 0,
    max: 1,
  },
  traderCommissionRate: {
    key: 'traderCommissionRate',
    displayName: 'Trader Commission Rate',
    description: 'Prozentsatz des Gewinns, den Trader als Provision erhalten',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    hiddenInParameterList: true,
    min: 0,
    max: 1,
  },
  appCommissionRate: {
    key: 'appCommissionRate',
    displayName: 'App Erfolgsprovision',
    description:
      'Plattform-Anteil am Investoren-Gewinn (Erfolgsprovision). In der Collection Bill als ein Posten „Commission“ zusammen mit der Trader-Provision ausgewiesen; Buchung auf 8400 Provisionserlös (PLT-REV-COM).',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    hiddenInParameterList: true,
    min: 0,
    max: 1,
  },
  initialAccountBalance: {
    key: 'initialAccountBalance',
    displayName: 'Initial Account Balance',
    description:
      'Startguthaben für neue Konten (0 € = kein autom. Startguthaben; Anpassung nur hier, nicht in App-Code)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 1000000,
  },
  appServiceChargeRate: {
    key: 'appServiceChargeRate',
    displayName: 'App Service Charge',
    description: 'App-Servicegebühr als Prozentsatz',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 0.1,
  },
  appServiceChargeRateCompanies: {
    key: 'appServiceChargeRateCompanies',
    displayName: 'App Service Charge Companies',
    description: 'App-Servicegebühr für Unternehmenskonten als Prozentsatz',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 0.1,
  },
  withholdingTaxRate: {
    key: 'withholdingTaxRate',
    displayName: 'Abgeltungsteuersatz',
    description: 'Basissatz der Kapitalertragsteuer (nur relevant bei Plattform-Abführung).',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  solidaritySurchargeRate: {
    key: 'solidaritySurchargeRate',
    displayName: 'Solidaritätszuschlag',
    description: 'Zuschlag auf die Abgeltungsteuer (nur relevant bei Plattform-Abführung).',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  vatRate: {
    key: 'vatRate',
    displayName: 'Umsatzsteuer (MwSt.)',
    description: 'Umsatzsteuersatz für gebührenrelevante Ausweise',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  taxCollectionMode: {
    key: 'taxCollectionMode',
    displayName: 'Abgeltungsteuer',
    description: 'Steuert die Abführung von Abgeltungsteuer inkl. Solidaritätszuschlag und ggf. Kirchensteuer.',
    type: 'string',
    category: 'tax',
    isCritical: true,
  },
  legalAppName: {
    key: 'legalAppName',
    displayName: 'App Name',
    description: 'Kanonischer App-Name für Branding-Token (z. B. {{APP_NAME}}) in Rechtstexten und UI.',
    type: 'string',
    category: 'system',
    isCritical: true,
  },
  minimumCashReserve: {
    key: 'minimumCashReserve',
    displayName: 'Minimum Cash Reserve',
    description: 'Mindestbetrag, den Benutzer auf dem Konto behalten müssen',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0.01,
    max: 1000,
  },
  minInvestment: {
    key: 'minInvestment',
    displayName: 'Mindestinvestmentbetrag',
    description: 'Mindestbetrag pro Investment (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0.01,
    max: 1000000,
  },
  maxInvestment: {
    key: 'maxInvestment',
    displayName: 'Maximuminvestmentbetrag',
    description: 'Höchstbetrag pro Investment (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0.01,
    max: 1000000,
  },
  daily_transaction_limit: {
    key: 'daily_transaction_limit',
    displayName: 'Daily Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Tag über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 100,
    max: 500000,
  },
  weekly_transaction_limit: {
    key: 'weekly_transaction_limit',
    displayName: 'Weekly Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Woche über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 1000,
    max: 500000,
  },
  monthly_transaction_limit: {
    key: 'monthly_transaction_limit',
    displayName: 'Monthly Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Monat über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 5000,
    max: 2000000,
  },
  maxTraderPartialSells: {
    key: 'maxTraderPartialSells',
    displayName: 'Max. Teil-Verkäufe (Trader)',
    description:
      '0 = nur Vollverkauf (keine Teil-Sells); 1–3 = maximale Anzahl Teil-Verkäufe pro Trade vor Abschluss (Trader-App / Server). Unabhängig von der Investor-Anzeige.',
    type: 'number',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 3,
  },
  maxTraderOpenDepotPositions: {
    key: 'maxTraderOpenDepotPositions',
    displayName: 'Max. offene Depot-Positionen (Trader)',
    description:
      'Globales Limit für gleichzeitig offene Trader-Depot-Positionen (Kauf abgeschlossen, Restmenge > 0). Standard: 5. Pro Trader unter Benutzer → Details individuell überschreibbar (4-Augen). Server blockiert neue Käufe via executePairedBuy.',
    type: 'number',
    category: 'financial',
    isCritical: true,
    min: 1,
    max: 50,
  },
  poolBalanceDistributionThreshold: {
    key: 'poolBalanceDistributionThreshold',
    displayName: 'Pool Distribution Threshold',
    description:
      'Schwellenwert für die Pool-Verteilung. Logik noch nicht implementiert; reserviert für spätere Option „Restbeträge sammeln bis Schwellenwert“, dann Auszahlung.',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 1,
    max: 100,
  },
  maxPoolMirrorBuyOrderAmount: {
    key: 'maxPoolMirrorBuyOrderAmount',
    displayName: 'Pool-Mirror-Buy-Obergrenze',
    description:
      'Maximale Brutto-Summe (EUR) für einen Pool-Mirror-Kauf (Buy-Order) und für reserviertes Investoren-Kapital je Trader bis zum nächsten Trade. 0 = keine Obergrenze. Bei Erreichen: neue Investments blockiert; Investoren können Benachrichtigung aktivieren.',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 50000000,
  },
  minTraderBuyOrderAmount: {
    key: 'minTraderBuyOrderAmount',
    displayName: 'Mindest-Kaufbetrag (Trader)',
    description:
      'Mindest-Brutto (EUR) für die Trader-eigene Kauforder (TRADER-Leg bei executePairedBuy bzw. Einzelkauf). 0 = deaktiviert. Pool-Mirror-Käufe (Investoren-Kapital) sind hiervon ausgenommen.',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 1000000,
  },
  maximumRiskExposurePercent: {
    key: 'maximumRiskExposurePercent',
    displayName: 'Maximum Risk Exposure (%)',
    description: 'Empfohlener maximaler Prozentsatz des Vermögens, der dem Risiko ausgesetzt werden soll (Dashboard-Hinweis)',
    type: 'percent_display',
    category: 'display',
    isCritical: false,
    min: 0,
    max: 100,
  },
  showDocumentReferenceLinksInAccountStatement: {
    key: 'showDocumentReferenceLinksInAccountStatement',
    displayName: 'Kontoauszug: Links zu Buchungsbelegen',
    description:
      'Steuert in der App, ob Buchungszeilen im Kontoauszug (rollierend und Monatsansicht) als Links zur jeweiligen Beleg-/Dokument-Ansicht dienen (Konfiguration `display.showDocumentReferenceLinksInAccountStatement`).',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  showCommissionBreakdownInCreditNote: {
    key: 'showCommissionBreakdownInCreditNote',
    displayName: 'Trader: Commission Breakdown (Dev/QA)',
    description:
      'Steuert in der Trader-App den Commission-Breakdown: Info-Icon in der Trade-Tabelle sowie Aufschlüsselung in der Gutschrift (CN-) (`display.showCommissionBreakdownInCreditNote`). In Production deaktiviert lassen — Ops-SSOT ist Admin Summary Report → Pool-Mirror-Trade Investoren (Spalten Gewinn-Anteil / Provision).',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  walletActionModeGlobal: {
    key: 'walletActionModeGlobal',
    displayName: 'Konto-Aktionsmodus (Global)',
    description: 'Gilt für alle Nutzer als globale Obergrenze. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeInvestor: {
    key: 'walletActionModeInvestor',
    displayName: 'Konto-Aktionsmodus (Rolle: Investor)',
    description: 'Rollenbezogene Steuerung für Investor-Nutzer. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeTrader: {
    key: 'walletActionModeTrader',
    displayName: 'Konto-Aktionsmodus (Rolle: Trader)',
    description: 'Rollenbezogene Steuerung für Trader-Nutzer. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeIndividual: {
    key: 'walletActionModeIndividual',
    displayName: 'Konto-Aktionsmodus (Account: Privatperson)',
    description: 'Account-Typ-spezifische Steuerung für Privatpersonen. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeCompany: {
    key: 'walletActionModeCompany',
    displayName: 'Konto-Aktionsmodus (Account: Company)',
    description: 'Account-Typ-spezifische Steuerung für Company-Konten. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  serviceChargeInvoiceFromBackend: {
    key: 'serviceChargeInvoiceFromBackend',
    displayName: 'Servicegebühr-Rechnung über Server',
    description:
      'Wenn aktiv, legt der Parse-Server die App-Servicegebühr-Rechnung idempotent über die Cloud Function `bookAppServiceCharge` an (ADR-007). Wenn inaktiv, bleibt der Legacy-Pfad über die iOS-`InvoiceService`-Persistenz bestehen.',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
  serviceChargeLegacyClientFallbackEnabled: {
    key: 'serviceChargeLegacyClientFallbackEnabled',
    displayName: 'Legacy-Client-Fallback aktiv',
    description:
      'Fallback auf den alten iOS-Client-Pfad für Service-Charge-Invoices. Für vollständiges SSOT nach Stabilisierung deaktivieren.',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  serviceChargeLegacyDisableAllowedFrom: {
    key: 'serviceChargeLegacyDisableAllowedFrom',
    displayName: 'Legacy-Deaktivierung erlaubt ab',
    description:
      'Frühestes Datum (YYYY-MM-DD), ab dem der Legacy-Fallback deaktiviert werden darf.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  investorMonetaryServerOnly: {
    key: 'investorMonetaryServerOnly',
    displayName: 'Investor-Beträge nur vom Server',
    description:
      'Wenn aktiv, zeigt die iOS-App für Investoren keine lokal berechneten €-Beträge (Collection Bill, Completed Investments, Cash Distribution). Fehlende Belege → Fehler statt Schätzung. Standard: aktiv.',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
  traderMonetaryServerOnly: {
    key: 'traderMonetaryServerOnly',
    displayName: 'Trader-Beträge nur vom Server',
    description:
      'Wenn aktiv, nutzt die iOS-App für Trader keine lokal generierten Rechnungen/Kontoauszüge als Fallback. Fehlender Server-Kontoauszug → Fehlermeldung statt lokaler Invoice-Rechnung. Standard: aktiv.',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
  frontendReadonlyMode: {
    key: 'frontendReadonlyMode',
    displayName: 'Client: keine monetären Fallbacks',
    description:
      'Kill-Switch für Produktion: blockiert alle client-seitigen monetären Fallbacks und lokale Invoice-Generierung (Investor + Trader). Standard: aus (nur für Notfall/Härtung).',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  settlementGLOutboxEnabled: {
    key: 'settlementGLOutboxEnabled',
    displayName: 'Settlement GL Outbox (ADR-017)',
    description:
      'Wenn aktiv: AccountStatement und SettlementOutbox in einer Mongo-Transaktion; AppLedger-Paare werden asynchron vom Worker gebucht (kein synchrones fail-open GL mehr). Standard: aus (Rollout).',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  showInvestorPartialSellRealizations: {
    key: 'showInvestorPartialSellRealizations',
    displayName: 'Investor: Teil-Sell-Bereich anzeigen',
    description:
      'Wenn deaktiviert, sieht der Investor in der iOS-App unter Investments weder „Teil-Sell-Realisierungen (Active Investment)“ noch zugehörige Details — unabhängig davon, ob der Trader Teil-Verkäufe ausführt. Nur „Active Investments“ und „Completed Investments“. Standard: aus (weniger Verwirrung).',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
  showTraderDashboardInvestmentActiveStatus: {
    key: 'showTraderDashboardInvestmentActiveStatus',
    displayName: 'Trader-Depot: Investment-Pool Status anzeigen',
    description:
      'Steuert in der Trader-App im Depot bei den Positions-Kacheln, ob die Zeile „Investment-Pool“ (active / -) nach abgeschlossener Kauforder angezeigt wird (`display.showTraderDashboardInvestmentActiveStatus`). Standard: an. Änderung erfordert 4-Augen-Freigabe.',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  collectionBillServerLegs: {
    key: 'collectionBillServerLegs',
    displayName: 'Collection Bill: Server buyLeg/sellLeg (ADR-009)',
    description:
      'Wenn aktiv, liest iOS Investor-Collection-Bills ausschließlich metadata.buyLeg/sellLeg vom Server. Fehlende Legs → „pending“ statt lokaler Neuberechnung. Standard: aktiv.',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
};
