import type { ConfigurationParameter } from './types';

/** Parameter definitions with metadata (values come from backend / resolveConfig). */
export const PARAMETER_DEFINITIONS: Record<string, Omit<ConfigurationParameter, 'value'>> = {
  traderCommissionRate: {
    key: 'traderCommissionRate',
    displayName: 'Trader Commission Rate',
    description: 'Prozentsatz des Gewinns, den Trader als Provision erhalten',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 1,
  },
  initialAccountBalance: {
    key: 'initialAccountBalance',
    displayName: 'Initial Account Balance',
    description:
      'Startguthaben für neue Konten (0 € = kein autom. Startguthaben; Anpassung nur hier, nicht in App-Code)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 1000000,
  },
  appServiceChargeRate: {
    key: 'appServiceChargeRate',
    displayName: 'App Service Charge',
    description: 'App-Servicegebühr als Prozentsatz',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 0.1,
  },
  appServiceChargeRateCompanies: {
    key: 'appServiceChargeRateCompanies',
    displayName: 'App Service Charge Companies',
    description: 'App-Servicegebühr für Unternehmenskonten als Prozentsatz',
    type: 'percentage',
    category: 'financial',
    isCritical: true,
    min: 0,
    max: 0.1,
  },
  withholdingTaxRate: {
    key: 'withholdingTaxRate',
    displayName: 'Abgeltungsteuersatz',
    description: 'Basissatz der Kapitalertragsteuer (nur relevant bei Plattform-Abführung).',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  solidaritySurchargeRate: {
    key: 'solidaritySurchargeRate',
    displayName: 'Solidaritätszuschlag',
    description: 'Zuschlag auf die Abgeltungsteuer (nur relevant bei Plattform-Abführung).',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  vatRate: {
    key: 'vatRate',
    displayName: 'Umsatzsteuer (MwSt.)',
    description: 'Umsatzsteuersatz für gebührenrelevante Ausweise',
    type: 'percentage',
    category: 'tax',
    isCritical: true,
    min: 0,
    max: 1,
  },
  taxCollectionMode: {
    key: 'taxCollectionMode',
    displayName: 'Abgeltungsteuer',
    description: 'Steuert die Abführung von Abgeltungsteuer inkl. Solidaritätszuschlag und ggf. Kirchensteuer.',
    type: 'string',
    category: 'tax',
    isCritical: true,
  },
  legalAppName: {
    key: 'legalAppName',
    displayName: 'App Name',
    description: 'Kanonischer App-Name für Branding-Token (z. B. {{APP_NAME}}) in Rechtstexten und UI.',
    type: 'string',
    category: 'system',
    isCritical: true,
  },
  minimumCashReserve: {
    key: 'minimumCashReserve',
    displayName: 'Minimum Cash Reserve',
    description: 'Mindestbetrag, den Benutzer auf dem Konto behalten müssen',
    type: 'currency',
    category: 'financial',
    isCritical: false,
    min: 0.01,
    max: 1000,
  },
  minInvestment: {
    key: 'minInvestment',
    displayName: 'Mindestinvestmentbetrag',
    description: 'Mindestbetrag pro Investment (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: false,
    min: 0.01,
    max: 1000000,
  },
  maxInvestment: {
    key: 'maxInvestment',
    displayName: 'Maximuminvestmentbetrag',
    description: 'Höchstbetrag pro Investment (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: false,
    min: 0.01,
    max: 1000000,
  },
  daily_transaction_limit: {
    key: 'daily_transaction_limit',
    displayName: 'Daily Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Tag über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 100,
    max: 500000,
  },
  weekly_transaction_limit: {
    key: 'weekly_transaction_limit',
    displayName: 'Weekly Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Woche über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 1000,
    max: 500000,
  },
  monthly_transaction_limit: {
    key: 'monthly_transaction_limit',
    displayName: 'Monthly Transaction Limit',
    description: 'Maximaler Gesamtbetrag pro Monat über alle Transaktionen (EUR)',
    type: 'currency',
    category: 'financial',
    isCritical: true,
    min: 5000,
    max: 2000000,
  },
  poolBalanceDistributionThreshold: {
    key: 'poolBalanceDistributionThreshold',
    displayName: 'Pool Distribution Threshold',
    description:
      'Schwellenwert für die Pool-Verteilung. Logik noch nicht implementiert; reserviert für spätere Option „Restbeträge sammeln bis Schwellenwert“, dann Auszahlung.',
    type: 'currency',
    category: 'financial',
    isCritical: false,
    min: 1,
    max: 100,
  },
  maximumRiskExposurePercent: {
    key: 'maximumRiskExposurePercent',
    displayName: 'Maximum Risk Exposure (%)',
    description: 'Empfohlener maximaler Prozentsatz des Vermögens, der dem Risiko ausgesetzt werden soll (Dashboard-Hinweis)',
    type: 'percent_display',
    category: 'display',
    isCritical: false,
    min: 0,
    max: 100,
  },
  showDocumentReferenceLinksInAccountStatement: {
    key: 'showDocumentReferenceLinksInAccountStatement',
    displayName: 'Kontoauszug: Links zu Buchungsbelegen',
    description:
      'Steuert in der App, ob Buchungszeilen im Kontoauszug (rollierend und Monatsansicht) als Links zur jeweiligen Beleg-/Dokument-Ansicht dienen (Konfiguration `display.showDocumentReferenceLinksInAccountStatement`).',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  walletActionModeGlobal: {
    key: 'walletActionModeGlobal',
    displayName: 'Konto-Aktionsmodus (Global)',
    description: 'Gilt für alle Nutzer als globale Obergrenze. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeInvestor: {
    key: 'walletActionModeInvestor',
    displayName: 'Konto-Aktionsmodus (Rolle: Investor)',
    description: 'Rollenbezogene Steuerung für Investor-Nutzer. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeTrader: {
    key: 'walletActionModeTrader',
    displayName: 'Konto-Aktionsmodus (Rolle: Trader)',
    description: 'Rollenbezogene Steuerung für Trader-Nutzer. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeIndividual: {
    key: 'walletActionModeIndividual',
    displayName: 'Konto-Aktionsmodus (Account: Privatperson)',
    description: 'Account-Typ-spezifische Steuerung für Privatpersonen. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  walletActionModeCompany: {
    key: 'walletActionModeCompany',
    displayName: 'Konto-Aktionsmodus (Account: Company)',
    description: 'Account-Typ-spezifische Steuerung für Company-Konten. Erfordert 4-Augen-Freigabe.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
  serviceChargeInvoiceFromBackend: {
    key: 'serviceChargeInvoiceFromBackend',
    displayName: 'Servicegebühr-Rechnung über Server',
    description:
      'Wenn aktiv, legt der Parse-Server die App-Servicegebühr-Rechnung idempotent über die Cloud Function `bookAppServiceCharge` an (ADR-007). Wenn inaktiv, bleibt der Legacy-Pfad über die iOS-`InvoiceService`-Persistenz bestehen.',
    type: 'boolean',
    category: 'display',
    isCritical: false,
  },
  serviceChargeLegacyClientFallbackEnabled: {
    key: 'serviceChargeLegacyClientFallbackEnabled',
    displayName: 'Legacy-Client-Fallback aktiv',
    description:
      'Fallback auf den alten iOS-Client-Pfad für Service-Charge-Invoices. Für vollständiges SSOT nach Stabilisierung deaktivieren.',
    type: 'boolean',
    category: 'display',
    isCritical: true,
  },
  serviceChargeLegacyDisableAllowedFrom: {
    key: 'serviceChargeLegacyDisableAllowedFrom',
    displayName: 'Legacy-Deaktivierung erlaubt ab',
    description:
      'Frühestes Datum (YYYY-MM-DD), ab dem der Legacy-Fallback deaktiviert werden darf.',
    type: 'string',
    category: 'display',
    isCritical: true,
  },
};
